name: U6 BOT

on:
  schedule:
    - cron: "1 */6 * * *"  # Toutes les 6 heures
  workflow_dispatch:       # Permet de déclencher manuellement ce workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py discord.js
        
    - name: Run Discord Bot (with 30 minute timeout)
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        node index.js
